### ISSUE TITLE
Question re: dl and dd

### ISSUE THREAD

**Issue by sarahdesmarais** [sarahdesmarais/content-semantics#1]
In markbot, I receive the following message for **Line 50**.

**Element dl is missing a required instance of child element dd.**

I'm not entirely sure how to fix this. Can you help? @thomasjbradley

**Comment by thomasjbradley** [comment]
Did you figure it out?

**Comment by sarahdesmarais** [comment]
Yes, I kept working on it and figured it out!

Thanks,
Sarah
